FROM public.ecr.aws/lambda/python:3.12

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Copy function code
COPY src/face_recognition.py ${LAMBDA_TASK_ROOT}

COPY src/torch-2.2.2+cpu-cp312-cp312-linux_x86_64.whl ${LAMBDA_TASK_ROOT}
COPY src/torchvision-0.17.2+cpu-cp312-cp312-linux_x86_64.whl ${LAMBDA_TASK_ROOT}

RUN pip install ${LAMBDA_TASK_ROOT}/torch-2.2.2+cpu-cp312-cp312-linux_x86_64.whl
RUN pip install --find-links . ${LAMBDA_TASK_ROOT}/torchvision-0.17.2+cpu-cp312-cp312-linux_x86_64.whl

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

# Install the specified packages
RUN pip install -r requirements.txt


# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "face_recognition.handler" ]